name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  # Scheduled trigger checks for breakage caused by changes to external resources (libraries, platforms)
  schedule:
    # run every Saturday at 3 AM UTC
    - cron: "0 3 * * 6"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports
      ARDUINOCORE_MBED_STAGING_PATH: extras/ArduinoCore-mbed
      ARDUINOCORE_API_STAGING_PATH: extras/ArduinoCore-API

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:mbed:envie_m7
            platform-name: arduino:mbed
            platforms: |
              - source-path: extras/ArduinoCore-mbed
                name: arduino:mbed
            libraries: |
              - name: Arduino_DebugUtils
            sketch-paths: |
              - examples/OTA_Qspi_Flash
              - examples/OTA_Qspi_Flash_Ethernet
              - examples/OTA_SD_Portenta
              - examples/OTA_Usage_Portenta
              - examples/LZSS
              - examples/OTA_Qspi_Flash_download_onthefly
          - fqbn: arduino:mbed_nicla:nicla_vision
            platform-name: arduino:mbed_nicla
            platforms: |
              - source-path: extras/ArduinoCore-mbed
                name: arduino:mbed_nicla
            libraries: |
              - name: Arduino_DebugUtils
            sketch-paths: |
              - examples/OTA_Qspi_Flash
              - examples/OTA_Usage_Portenta
              - examples/LZSS
              - examples/OTA_Qspi_Flash_download_onthefly
          - fqbn: arduino:mbed_opta:opta
            platform-name: arduino:mbed_opta
            platforms: |
              - source-path: extras/ArduinoCore-mbed
                name: arduino:mbed_opta
            libraries: |
              - name: Arduino_DebugUtils
            sketch-paths: |
              - examples/OTA_Qspi_Flash
              - examples/OTA_Qspi_Flash_Ethernet
              - examples/OTA_Usage_Portenta
              - examples/LZSS
              - examples/OTA_Qspi_Flash_download_onthefly
          - fqbn: arduino:mbed_giga:giga
            platform-name: arduino:mbed_giga
            platforms: |
              - source-path: extras/ArduinoCore-mbed
                name: arduino:mbed_giga
            libraries: |
              - name: Arduino_DebugUtils
            sketch-paths: |
              - examples/OTA_Qspi_Flash
              - examples/OTA_Usage_Portenta
              - examples/LZSS
              - examples/OTA_Qspi_Flash_download_onthefly

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout ArduinoCore-mbed
        if: matrix.board.platform-name == 'arduino:mbed'
        uses: actions/checkout@v4
        with:
          repository: arduino/ArduinoCore-mbed
          path: ${{ env.ARDUINOCORE_MBED_STAGING_PATH }}

      - name: Checkout ArduinoCore-API
        # This step only needed when the Arduino mbed-Enabled Boards platform sourced from the repository is being used
        if: matrix.board.platform-name == 'arduino:mbed'
        uses: actions/checkout@v4
        with:
          repository: arduino/ArduinoCore-API
          path: ${{ env.ARDUINOCORE_API_STAGING_PATH }}

      - name: Install ArduinoCore-API
        # This step only needed when the Arduino mbed-Enabled Boards platform sourced from the repository is being used
        if: matrix.board.platform-name == 'arduino:mbed'
        run: |
          mv "${{ env.ARDUINOCORE_API_STAGING_PATH }}/api" "${{ env.ARDUINOCORE_MBED_STAGING_PATH }}/cores/arduino"

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            ${{ matrix.board.libraries }}
          sketch-paths: |
            ${{ matrix.board.sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
